actix/actix

src/address.rs
Hi, loving using this library at the moment. I just thought I'd add some convenience to using boxed `Subscriber`s so that they can be cloned using `.clone()`.
=> Add convenience impl for boxed Subscriber objects.

guide/src/qs_03.md
The link to the Message trait was pointed towards the Actor trait, changed to point towards the Message trait.
=> Message link was pointing to Actor trait

src/contextimpl.rs, tests/test_context.rs
The iteration range is calculated once before starting the loop. During
the iterations the container might change it's size and the index access
fails. This patch is a minimal invasive modification fix in order to
keep the index access style used in `ContextImpl`.
Fixes #66.
=> Fix index usage during iteration for future cancellation

examples/mock.rs, src/actors/mocker.rs, src/actors/mod.rs, src/actors/resolver.rs, src/registry.rs
This PR allows SystemServices and ArbiterServices to be mocked for tests. docs and stuff will be added soon.
You can do something like:
```
// in global scope
#[cfg(test)]
type HTTPClient = Mocker<rita_common::http_client::HTTPClient>;
#[cfg(not(test))]
type HTTPClient = rita_common::http_client::HTTPClient;
// in a test
let _: Addr<Syn, _> = HTTPClient::start_reg(|_| { HTTPClient::mock(Box::new(|msg, ctx| {
assert_eq!(msg.downcast_ref::<Hello>(), Some(&Hello{
my_id: LocalIdentity {
wg_port: 60000,
global: SETTING.get_identity()
},
to: SocketAddr::V4(SocketAddrV4::new("1.1.1.1".parse().unwrap(), 4876))
}));
let ret: Result<LocalIdentity, Error> = Ok(LocalIdentity{
wg_port: 60000,
global: SETTING.get_identity(),
});
Box::new(Some(ret))
}))});
// now calls to HTTPClient::from_registry() …
```
=> Add mocker actor and registry start function

README.md
I was clicking through, and observed that the existing links were broken.
=> Update README.md: fix doc links for Unsync + Syn

src/address/channel.rs, src/address/message.rs, src/address/mod.rs
I think `maybe_park` should in Arc as Atomic is just Cell by itself, with Arc all cloned addrs should get the same `maybe_parked`
In addition to that I added test case to verify that addr sender gets full.
Note that it seems that `Actor::started` gets called only on initial send gets spawned, so current test is kinda work around of this limitation.
=> Addr should Arc maybe_park and add tests for capacity

CHANGES.md, Cargo.toml, src/arbiter.rs, src/system.rs, tests/test_arbiter.rs
When an Actor panics in an Arbiter, the Arbiter thread stops but no
other action is taken, the rest of the program continues to run. Only if
a sender is using try_send or send will they notice the failure. This
can lead to surprising circumstances where a program will appear to be
running but instead silently misbehaving or ready to explode on the next
message to that Actor (as a panic while processing the sent message does
_not_ fail initially).
Given that a panic is usually indicative of a fairly abnormal condition,
it's not necessarily correct to even restart execution in those cases.
For instance, `Mutex` will poison its self if the MutexGuard is dropped
while the thread is panicking. It's also usually desirable to exit the
program and let process supervision handle reinitializing the …
=> Arbiter: optionally stop system if Actor/Arbiter panics

.appveyor.yml
1. Removes x32 GNU jobs
2. Remove beta jobs. Considering we have nightly to test against, I think beta testing is redundant.
=> Lessen numbers of jobs for AppVeyor

Cargo.toml, src/arbiter.rs
Updates uuid to the latest release (0.6 to 0.7) which renamed `hyphenated()` to `to_hyphenated_ref()` and `simple()` to `to_simple_ref()`.
=> Update uuid to 0.7

src/fut/mod.rs
Please ensure "or" preserves the intended meaning of the sentence before accepting this change.
=> Correct spelling

README.md
The example doesn't compile as it is now. I just made the minimum changes to get it running.
=> No longer required to use Syn in README.md example.

CHANGES.md, src/actors/resolver.rs, src/address/message.rs, src/arbiter.rs, src/clock.rs, src/contextitems.rs, src/fut/stream_timeout.rs, src/fut/timeout.rs, src/lib.rs, src/system.rs, src/utils.rs
Tokio's `Registry` allows to set a custom `Clock` instance, which makes it possible to mock all timer related functions in tests. This PR adds the option to set that clock in the `System`'s runtime as well as override it in each `Arbiter`.
There is now `System::builder()`, which allows to set that clock instance and then build a `SystemRunner`. The type level docs have an example for that. It is not publicly exported, just like the Arbiter builder is not exported. Let me know, if you'd like to change that.
To make `Clock`, `Now` (the trait behind it) and `clock::now()` more accessible, this PR also adds a new public `actix::clock` module which contains a basic re-export of `tokio_timer::clock`. That way, users do not have to explicitly add `tokio_timer` to their own crate's dependencies. …
=> Use tokio_timer's Clock abstraction

src/contextimpl.rs, tests/test_context.rs
Canceled handles are generally consumed in the "process items" loop, but
the loop never runs if there's no item to process. As a result, the handles
are left unprocessed and the 'outer loop never resolves. This patch addresses
the issue by discarding the canceled handles if there's no item still alive.
The test case is a bit hairy. It wouldn't finish without the fix. I couldn't
come up with a better idea.
=> fix infinite loop in ContextFut::poll() caused by late cancel_future()

CHANGES.md, Cargo.toml, MIGRATION.md, src/actors/resolver.rs
trust-dns-resolver 0.10.0 has additional, useful options (e.g., max TTL) that can be passed in via ResolverOpts. These newer options are not available in trust-dns-resolver 0.9.1, which is what Actix currently depends on. This pull request updates Actix to depend on trust-dns-resolver 0.10.
What trust-dns-resolver used to call ResolverFuture is now called AsyncResolver. When creating an AsyncResolver, instead of being given a Future which must be waited on to construct the Resolver, you are immediately given an AsyncResolver, plus a background task that must be spawned to perform DNS lookups (https://docs.rs/trust-dns-resolver/0.10.0/trust_dns_resolver/struct.AsyncResolver.html). This pull request essentially does the renaming of types, plus spawns the background task.
=> Updating trust-dns-resolver dependency to version 0.10.

Cargo.toml, src/sync.rs
As far as I can see, this should be a minor semver change. I hope I got the migration to the new crossbeam-channel API right so that the new code has the same behavior as the previous version.
=> Update crossbeam-channel to 0.3 and parking_lot to 0.7

src/registry.rs
I removed `MyActor1.start()` from the `SystemRegistry` example, as there would otherwise be two `MyActor1`'s running (since `MyActor2` starts a `MyActor1` when it tries to get `MyActor1` from the registry).
I also fixed some grammar/spelling and removed some extra lines.
=> Revise Registry comments and examples

src/lib.rs
As long as we're not changing runtime, we should note on tokio's current_thread limitation in case users are not familiar with tokio enough.
Closes #181
=> Add note on tokio runtime

src/actor.rs, src/actors/mocker.rs, src/actors/resolver.rs, src/actors/signal.rs, src/address/channel.rs, src/address/envelope.rs, src/address/message.rs, src/address/mod.rs, src/arbiter.rs, src/context.rs, src/fut/helpers.rs, src/handler.rs, src/io.rs, src/lib.rs, src/msgs.rs
This commit results from proof-reading the API docs throughout the
whole crate, excluding the `fut` module and its children.
Mostly, the changes are in the following areas:
- Use a consistent style, which is also used by the standard
library, for example:
- Using just "Registers ..." instead instead of "This method
registers" for functions.
- Use punctiation more consistently (no full stops in headings, but
about everywhere else).
- Missing articles and other minor stylistic issues.
- Some markup issues (e.g. missing backticks for identifiers).
Besides mere wording improvements, which I hope are indeed
improvements (I'm not a native speaker, but dare to say that I'm quite
confident in English), the following tweaks also were made along the
way:
- Export the `Builder` type from the private …
=> Improve the wording of public API documentation

Cargo.toml
Currently actix ends up pulling both 0.5 and 0.6:
```
trust-dns-proto v0.5.0
└── actix v0.7.10 (/home/fabrice/dev/actix)
trust-dns-proto v0.6.3
└── trust-dns-resolver v0.10.3
└── actix v0.7.10 (/home/fabrice/dev/actix)
```
Moving to 0.6 prevents that.
=> Bump trust-dns-proto to 0.6

src/actor.rs, src/address/channel.rs, src/address/mod.rs, src/context.rs
This change improves the examples for setting mailbox capacity,
it improves the documentation of stop and terminate, and adds
some extra comments for clarity in do_send.
Author: William Brown <william@blackhats.net.au>
=> Improve documentation and examples for some functions.

src/contextimpl.rs
Recently rustdoc started issuing compiler warnings for doc comments above macro expansions. Moving this comment inside the macro resolves that. However, this comment still doesn't show up in the documentation, because the struct in question is not publicly reachable. 
So for consistency I remove the pub. As an alternative, it might be `pub( crate )`. Please modify to your liking.
`cargo test --all-features` runs fine. As some extra test I thought I run all tests on actix-web as well, but I can't get actix-web to compile with a local actix, so ... dunno... 
ps: I'm using nightly compiler
=> Fix compiler warning because of doc comment in the wrong place

Cargo.toml, tests/derive.rs
Related: https://github.com/actix/actix-derive/pull/14
Awaiting new release of actix-derive before CI tests can pass. I've ran tests using a path dependency to a local clone of actix-derive to make sure the tests pass.
=> Add derive tests for MessageResponse

src/io.rs, tests/test_sink.rs
A `futures::sink::Sink` wrapper for writing messages into a stream
from within a Actor. It allows more the use of custom sink objects
(or the use of channels).
It's an addition to `actix::io::FramedWrite<AsyncWrite, Encoder>`
and `actix::io::Writer<AsyncWrite>`. Both of those induce copies
into the inner buffer that can be sometime avoid with custom sink.
=> Add actix::io::SinkWrite<Sink>: A `Sink` IO wrapper

examples/chat/Cargo.toml, examples/chat/src/client.rs, examples/chat/src/codec.rs, examples/chat/src/main.rs, examples/chat/src/server.rs, examples/chat/src/session.rs
This allows eliminating all the `extern crate` statements from the
chat example source code.
=> examples chat: Switch to 2018 edition

examples/chat/src/client.rs, examples/chat/src/main.rs
- `tokio_io::codec::FramedRead` is a deprecated alias to
`tokio_codec::FramedRead`.
- No longer ignore the `Result` returned by `actix::System::run()`.
=> examples chat: Fix warnings

src/address/mod.rs
Since `MailboxError` does not have an underlying error which caused
it, and the `std::error::Error::description()` method is
soft-deprecated ("new `impl`s can omit it", to quote the standard
library), an empty implementation suffices.
=> Add `std::error::Error` implementation for `MailboxError`

README.md, examples/ring.rs, src/actor.rs, src/actors/resolver.rs, src/context.rs, src/contextimpl.rs, src/fut/stream_and_then.rs, src/io.rs, src/lib.rs, src/registry.rs, src/stream.rs, src/supervisor.rs, src/sync.rs, src/utils.rs, tests/derive.rs, tests/test_fut.rs, tests/test_sink.rs, tests/test_sync.rs
These are no longer needed in the 2018 edition, and their `macro_use`
variants can be replaced with explicitly importing the macros needed.
=> Eliminate `extern crate` statements

CHANGES.md, examples/chat/Cargo.toml, examples/chat/src/main.rs
This also serves as an example of how to replace the functionality of
the removed signal actor. An appropriate reference in `CHANGES.md` is
added.
=> examples chat: Add signal handling in server

.appveyor.yml
Add some directories to `PATH` to avoid failing build in AppVeyor
=> Avoid failing build in AppVeyor

src/fut/mod.rs, src/utils.rs
Use `rustfmt` and `clippy` prefixes.
=> Fix few clippy warnings

examples/chat/src/main.rs, src/actors/mocker.rs, src/address/channel.rs, src/address/envelope.rs, src/address/message.rs, src/address/mod.rs, src/contextimpl.rs, src/contextitems.rs, src/handler.rs, src/registry.rs, src/sync.rs, src/utils.rs
Add explicit `dyn`s and rename lint attribute
=> Fix clippy warnings

CHANGES.md, Cargo.toml, src/handler.rs
The type signature for `ResponseFuture` was causing issues with `Unpin` and `GenFuture`.
=> Update type signature for ResponseFuture to match BoxFuture

examples/ring.rs
This PR fixes the ring example, which terminates after just a few tens of messages is sent, instead of waiting for all messages to flow through the ring, which makes for a very misleading benchmark (which is why I noticed.)
Also adds some more informative output, such as messages sent per second.
I know very little of actix, as I started playing around with it today, and I expect someone who knows actix to be able to do better, but this is at least an improvement over the current state.
=> Fix broken Ring example

src/handler.rs
Since Futures doesn't require a Ok and an Err type anymore, I see no reason for the `MessageResponse<A, M>` for a `ResponseActFuture<A, T>` to require that `T` is a `Result`.
The current code also doesn't add any constrains to the `I` and `E` used on the `Result<I, E>`, so using any static type `T` for the `ResponseActFuture` here does seam more appropriated since it's more generic.
=> Lower constrain on MessageResponse for ResponseActFuture

CHANGES.md, src/handler.rs
Fixes #315 
> The regression actually appeared here:  
> https://github.com/actix/actix/commit/aeb7bd15ea8793e5f00f17caefb01eb678136c2e#diff-057239071828d04f3e4c9ce9b814cdb0L179-L185  
> where
> ```rust
> actix_rt::spawn(self.then(move |res| {
>     if let Some(tx) = tx {
>         tx.send(res)
>     }
> ```
> was replaced with
> ```rust
> actix_rt::spawn(async move {
>     if let Some(tx) = tx {
>         tx.send(self.await)
>     }
> ```
> so the `Stream` is polled only if `tx` is provided.
=> Fix polling ResponseFuture returned by Handler (#315)

Cargo.toml
Without the `io-util` flag, compiling actix with the default features disabled results in the following error:
```
error[E0432]: unresolved import `tokio::io::AsyncWriteExt`
--> src\io.rs:12:29
|
12 | use tokio::io::{AsyncWrite, AsyncWriteExt};
|                             ^^^^^^^^^^^^^
|                             |
|                             no `AsyncWriteExt` in `io`
|                             help: a similar name exists in the module: `AsyncWrite`
error[E0599]: no method named `write` found for type `std::cell::RefMut<'_, T>` in the current scope
--> src\io.rs:418:34
|
418 |             let _ = async_writer.write(&inner.buffer);
|                                  ^^^^^ method not found in `std::cell::RefMut<'_, T>`
|
= help: items from traits can only be used if the trait is …
```
=> Enable the Tokio feature "io-util" 

src/fut/mod.rs, src/handler.rs
Recently there has been quite a feel people on the repo and on gitter asking and discussing about how to asynchronously handle messages using Actix. This PR mains at improving the documentation of the offered types and implementations and tries to guide uses to the right types upon navigating the docs. I've added some examples to the types in order illustrate a littler better how to use the API as well.
I encourage users to point out any misleading, confusing or incomplete points in the doc related to asynchronous message handling so we can all make the library a littler easier to use.
=> Improves documentation on how to asynchronously handle messages

examples/README.md
Fix examples/README.md.
Fibonnaci => Fibonacci
=> Fix typo for examples/README.md

src/contextimpl.rs, src/fut/chain.rs, src/fut/either.rs, src/fut/result.rs, src/supervisor.rs, src/sync.rs
This removes several uses of `unsafe`, while making the code more readable.
There are still some uses of `Pin::get_unchecked_mut` remaining. There's no straightforward way to replace them with `#[pin_project]`. There are two main reasons for this:
1. `#[pin_project]` lacks the ability to project through an `Option`. I *think* that it should be possible to do this is a sound manner, but I'm not 100% certain. 
2. The code structure doesn't make it clear that a pinned type is never moved. For example, `StreamFold::poll` calls `mem::replace` on a `State` value, but also pins values inside `Stream::Ready` and `Stream::Processing`. It's not obvious to me whether or not the current code is sound.
=> Replace some uses of `Pin::get_unchecked_mut` with `pin_project`

examples/README.md
I was on the page https://github.com/actix/actix/tree/master/examples/chat/src wondering what dependencies I should add to 'Cargo.toml`, then I realized that https://github.com/actix/actix/tree/master/examples/chat has everything I need. 
This PR updates the link so it's less confusing.
=> Fix link to the chat example

CHANGES.md, src/handler.rs
This finishes the work started by @mocsy on #313.
Closes #313
=> Allows a more permissive handing of `ResponseFuture`

src/address/message.rs, src/fut/helpers.rs, src/fut/stream_fold.rs
After this PR, the only remaining use of `unsafe` with `Pin` comes from `impl ActorFuture for Box`.
=> Make more uses of Pin safe

src/contextimpl.rs, src/contextitems.rs, src/fut/mod.rs, src/handler.rs
This is a breaking change.
The previous impl was unsound: it allowed going from a `Pin<&mut Box<F>>`
to a `Pin<&mut F>`. However, the fact that `Box<T>` is `Unpin` for all
`T` means that it's possible to go from a `Pin<&mut Box<F>>` to a
`&mut Box<F>`. This allows a user to construct a `Pin<&mut F>`, and them
move the underlying `F` by obtaining a `&mut Box<F>` and calling
`mem::swap`.
The new impl adds an `Unpin` bound to `F`, bringing it in line with the
standard library's impl of `Future` for `Box<F>`.4
We can make `Box<F> where F: ActorFuture` easier to work with by
'porting' a `Future`-related impl from the standard library. By making
`Pin<Box<F>>` implement `ActorFuture` (e.g. you can call `poll` on a
`Pin<&mut Pin<Box<F>>>`), it's possible to avoid introducing extra
`Box`s in many …
=> Only implement `ActorFuture` for Box where `ActorFuture` is `Unpin`

CHANGES.md, Cargo.toml, src/actors/resolver.rs, tests/test_actors.rs
This also updates and fixes the `test_resolver` integration test and the example on `actors::resolver`, both which would finishing without any execution.
Closes #345
=> Upgrade Resolver Actor to use newest trust_dns versions

CHANGES.md, Cargo.toml, src/actors/resolver.rs, src/lib.rs
This fix should resolve #321 to enable moving actix-http specific trait implementations for actors to actix-http crate:
- https://github.com/actix/actix/blob/ba9f0a374462b80374ab9ecf5956c4a1265e7a87/src/lib.rs#L208
- https://github.com/actix/actix/blob/ba9f0a374462b80374ab9ecf5956c4a1265e7a87/src/actors/resolver.rs#L151
After this change applied and actix published to crates, we can make actix a dependency for actix-http and implement mentioned traits in the actix-http crate.
=> Removed actix-http dependency and http feature

CHANGES.md, src/actors/resolver.rs, src/fut/mod.rs, src/handler.rs
The main change here is that `ResponseActFuture<A, I>` is now defined as `Pin<Box<dyn ActorFuture<Output = I, Actor = A>>>` instead of the old `Box<dyn ActorFuture<Output = I, Actor = A>>`, which is a public API change.
As #348 got merged boxing a `ActorFuture` is not enough to keep access to trait's methods, the user should also `Pin` it. As this was a breaking change, I believe that changing the type of `ResponseActFuture` should make it more clear that responses using it should be `Pin` and therefore make migrations of old code easier. This also changes some internal codes to `Pin` their boxed `ActorFuture` and it does make code a little clear.
=> Enforce Pin on stored ActorFuture

.github/workflows/linux.yml, .github/workflows/windows.yml, tests/test_actor.rs
Test failed due to race condition where the test would finish before the actor had a change to stop. This moves the stop call to the actor, so it's always
called only when the actor actually stops.
One problem with this is that if something breaks on the lib cause the `Actor` to not stop as they should the test would not stop. @JohnTitor would this be a problem on the CI? I'm not sure what problems this would cause. If this is a problem I can add the code bellow to the test so least it's would be easy to see if tests start to break due to timeout, rather than just failing at the stopping count:
```Rust
actix_rt::spawn(async move {
delay_for(Duration::from_secs(5)).await;
panic!("System has not stopped time, are the actors stopping?")
});
```
fixes #354
=> Fix test_restart_sync_actor occasional fail

CHANGES.md, src/handler.rs, src/lib.rs, tests/test_atomic_response.rs
It has been pointed out and discussed on #308, #334 and on gitter a possible data race when handling messages asynchronously and a note about it has been added to the docs on #326. This offers a easy to use `MessageResponse` to the users that will be spawned into the Actor's context with a `AsyncContext::wait` call.
`AtomicResponse` allows messages responses generated by an `Actor` to have exclusive access over it, making it easier to process messages that need to stop the Actor from processing other futures but still leaving the runtime free to `poll` other spawned futures.
I also removed some unnecessary future wrapping used on other `MessageResponse` implementations.
=> Add new AtomicResponse

src/stream.rs, tests/test_actor.rs
The `loop` used would consume all available data from the `Stream`, however when handling very large streams the system would be blocked from processing other futures, like other messages, unless the handle makes the actor's `Context` wait. With this new impl only one is consumed at each pull but the task is informed that more progress could be processed right the way, this allow other futures to progress if the Runtime so decides.
The problem has been reported on #360, after looking at the `Future`implementation for [StreamFuture](https://docs.rs/futures/0.3.4/futures/stream/struct.StreamFuture.html) on futures-rs I do believe that processing a single item at a poll is a valid implementation. I've added `test_infinite_stream`, a new integration test to ensure we keep supporting this use …
=> Avoid looping on ActorFuture impl for ActorStream

.github/workflows/linux.yml
codecov-action doesn't require tokens anymore so we can accept PRs from fork repos now.
=> Upload coverage on PRs

Cargo.toml, src/registry.rs, src/stream.rs
Use `once_cell` over `lazy_static` to acquire macro-free. This adds additional dependency but I'm fine with that since the community seems to prefer `once_cell` nowadays.
=> Use `once_cell` over `lazy_static`

CHANGES.md, src/fut/stream_then.rs, tests/test_fut.rs
Old implementation would lose the stored future if it wasn't immediately ready
as reported on #375
I've also updated the `test_stream_timeout` to also use the `then` method so we ensure it doesn't break again in the future.
fixes #375
=> Fix ActorFuture::poll_next impl for StreamThen

.github/workflows/linux.yml, CHANGES.md, README.md, examples/chat/src/client.rs, src/lib.rs
Rustdoc now passes "doctest" when running in test mode.
=> Replace "cfg(test)" with "cfg(doctest)" for readme testing

CHANGES.md, Cargo.toml, src/contextimpl.rs
This ensures the `ContextFut` will not run when dropped if the event loop has already stopped. Which could cause crash in case of the runtime stopping with a spawned actor that didn't fully start.
fixes #372
=> Only poll dropped ContextFut if event loop is running

CHANGES.md, MIGRATION.md, src/io.rs, tests/test_sink.rs
fix actix/actix-web#1479
Moves `Sink::start_send` calls into the ActorFuture impl, and correctly guards with `Sink::poll_ready`, buffering items to be sent.
I think this is the key _(from `futures::sink::Sink::start_send` docs)_:
> Each call to this function must be preceded by a successful call to poll_ready which returned Poll::Ready(Ok(())).
Seems that the easiest way to achieve this is as implemented here; with an item buffer and calling poll_ready in the place where task context is available.
The existing `test_send_2` test seems to adequately test this implementation.
=> buffer write calls in SinkWrite

Cargo.toml
crates.io no longer shows that badge and we have it on README already so it's fine to remove.
=> Remove badge metadata

Cargo.toml, src/fut/chain.rs, src/fut/either.rs, src/fut/stream_fold.rs, src/fut/stream_map.rs, src/fut/stream_then.rs
pin-project will deprecate the project attribute due to some unfixable
limitations.
Refs: https://github.com/taiki-e/pin-project/issues/225
*Although the deprecation of the project attribute has not been released yet, this PR is submitted in advance to avoid the CI from being broken by deprecated warnings.*
=> Remove uses of pin_project::project attribute

CHANGES.md, src/address/message.rs
Removes `Request`'s `PhantomData<A>` field, as `A` is already constrained in `Request` (there is a `AddressSender<A>` field) and `PhantomData` just seems to be overlooked during previous `Request` refactoring.
<details>
<summary>HISTORY</summary>
Changes `Request`'s `PhantomData<A>` to `PhantomData<AtomicPtr<A>>` (which is always `Send` and `Sync`), which makes `Request` auto implement `Send` and `Sync` regardless if `A` is `Send` or `Sync`.
</details>
Fixes #405.
=> Make `Request` `Send` regardless of actor type

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/clippy-fmt.yml
Chore
Currently, we don't force contributors to format their PRs. I think it's worth checking code with rustfmt on CI since an unspecified number of people may touch the code and formatting commit is noisy to follow commit history.
I use stable rustfmt here for two reasons:
- nightly rustfmt enables unstable rules.
- nightly rustfmt is sometimes broken as it's managed as submodule rather than subtree like Clippy.
=> Check code with rustfmt not to introduce format commits

CHANGES.md, src/handler.rs
This is a *Feature* -  it allows users to write code that they previously couldn't due to an overly strict `where` clause.
This PR removes a the `Unpin` requirement from the `Response::fut()` constructor's `where` clause, allowing a `Response` to be constructed using an `async` block or result of an `async` function. 
Previously, a `Response` could only be constructed via combinators (`futures::FutureExt` and friends) and using an `async` block would result in a type error.
This should be fully backwards compatible because: 
1. Any type that is `T: Future + Unpin + 'static` is also `T: Future + 'static`
2. The user can't directly access the `ResponseTypeItem::Fut` variant. So they won't know it's changed from `Box<dyn Future>` to `Pin<Box<dyn …
=> Remove the Unpin requirement on Response::fut()

CHANGES.md, Cargo.toml, actix-derive/CHANGES.md, actix-derive/Cargo.toml, actix-derive/LICENSE-APACHE, actix-derive/LICENSE-MIT, actix-derive/README.md, actix-derive/rustfmt.toml, actix-derive/src/lib.rs, actix-derive/src/message.rs, actix-derive/src/message_response.rs, actix-derive/tests/test_macro.rs, src/lib.rs
Meta / Organisation
I often forget that actix-derive exists since it's in a separate repo. This way we can archive the old repo and keep track of the crate more easily.
=> move derive crate into workspace

CHANGES.md, examples/weak_addr.rs, examples/weak_recipient.rs, src/address/channel.rs, src/address/mod.rs, src/lib.rs, tests/test_address.rs
With this change you can now call `.recipient()` on `WeakAddr<A>` just
like on `Addr<A>`. In this case you get a `WeakRecipient<M>` that can
be upgraded to a `Recipient<M>`.
INSERT_PR_TYPE
Hi there,
I'm trying to convert my project to make greater use of `Recipient<M>` instead of `Addr<A>` since I believe it allows to loosen some tight coupling here and there. Unfortunately there is no equivalent to `WeakAddr<A>` for Recipients yet, so I cannot really use Recipients at the moment without running the risk of leaking objects.
Therefore I would like to suggest adding `WeakRecipients` to actix.
This PR supersedes #418, which was flawed. In that attempt I made the `Box` inside the `Recipient` an `Arc` and downgraded it.
you would call
```rust
let weak_rcp …
```
=> Add WeakRecipient (v2)

CHANGES.md, actix-derive/src/message.rs, src/sync.rs
Bug Fix
Not sure if this can be considered a bug but sync arbiter would want to spawn on current thread arbiter.
This means spawn nested sync arbiter would not work and no panic or error is shown.
This PR send the sync arbiter to current system and spawn it there to work around the requirement of current thread arbiter.
Closes #434
=> enable nested sync arbiters

CHANGES.md, src/address/envelope.rs, src/sync.rs
Refactor
Use generic type instead of associate type for `EnvelopeProxy`. As a result `SyncEnvelopeProxy` and `SyncContextEnvelope` are no longer bound to `Actor` type make them `Send` and no unsafe impl for it are needed.
=> remove unsafe on envelopes

CHANGES.md, Cargo.toml
Dependency bump
There are no breaking changes in the `crossbeam-channel` 0.5.0 changelog, so there are no required changes on `actix`'s side.
=> Bump crossbeam-channel from 0.4.x to 0.5.x

actix/src/mailbox.rs
Bug Fix
`Mailbox::poll` was actively polling another round on Pending in some cases.
This result in some waste atomic operations.
This PR would exit poll method directly on Pending.
=> remove waste poll of mailbox

actix/src/lib.rs
Feature
This re-exports `actix_rt::ArbiterHandle` since `Arbiter::current()` and `Arbiter::handle(&self)` now return this type, and `Actor::start_in_arbiter` expects this type as its first argument, so sometimes it is useful to be able to name the type, and currently you have to add `actix-rt` as an explicit dependency.
=> Re-export actix_rt::ArbiterHandle

actix-derive/src/message_response.rs, actix/CHANGES.md, actix/src/address/channel.rs, actix/src/contextitems.rs, actix/src/handler.rs, actix/src/lib.rs
Refactor
Remove `ResponseChannel` trait. 
It does not generic over channel type and impl only for `()` and `tokio::sync::oneshot::Sender`.
This would reduce the one generic type from `MessageResponse` trait
=> remove ResponseChannel trait

actix/CHANGES.md, actix/Cargo.toml, actix/src/actor.rs, actix/src/actors/resolver.rs, actix/src/context.rs, actix/src/contextimpl.rs, actix/src/contextitems.rs, actix/src/fut/chain.rs, actix/src/fut/either.rs, actix/src/fut/map.rs, actix/src/fut/mod.rs, actix/src/fut/ready_fut.rs, actix/src/fut/result.rs, actix/src/fut/stream_finish.rs, actix/src/fut/stream_fold.rs, actix/src/fut/stream_map.rs, actix/src/fut/stream_then.rs, actix/src/fut/stream_timeout.rs, actix/src/fut/then.rs, actix/src/fut/timeout.rs, actix/src/handler.rs, actix/src/io.rs, actix/src/stream.rs, actix/src/utils.rs
Refactor
Rework `ActorFuture` trait. 
Move Actor type bind to trait so the type impl `ActorFuture` is not constriant to Actor type.
This enables foreign types impl `ActorFuture` without a new type. (See `actix::fut::result` and `actix::fut::ready_fut`).
And more foreign types can be introduced to further reduce new type wrappers.
=> rework ActorFuture trait

actix/src/contextitems.rs, actix/src/stream.rs
Bug Fix
Sytle change on handling `ActorStream` and `ActorMessageStream`.
Use relaxed yield condition for `ActorStream`.
`ActorStream`  would yield and self wake up with every ready state.
This is to not starve other actor futures from executing when actor stream yield too quickly and too much.
That said this is also an overhead on the executor as the stream keep schedule itself when the above situation happen.
This PR takes a compromise and force yield the stream only when it has 16 consecutive ready on `Stream::poll_next`. This would reduce the burden of scheduler and at the same time keep other futures waiting for a bit longer before the yield happen.
Note: 16 is a random number here with no actual reason.
=> fix earger self wakeup of actor stream

actix/tests/test_address.rs, actix/tests/test_fut.rs
Bug Fix
Fix `test_weak_address` by waiting for the delay future to resolve.
Fix `test_stream_timeout` by relaxing the timeout duration and panic on non timed out output.
Separate actors for `tests::test_fut` between different tests.
=> fix test_weak_address/test_stream_timeout

actix/CHANGES.md, actix/src/address/mod.rs
According to the [C-CONV-TRAITS](https://rust-lang.github.io/api-guidelines/interoperability.html#c-conv-traits) of Rust API Guidelines,
The following conversion traits should never be implemented:
- `Into`
- `TryInto`
These traits have a blanket impl based on `From` and `TryFrom`. Implement those instead.
Code Style
=> Replace the Into implement to From<Addr> for Recipient and WeakRecipient

actix/CHANGES.md, actix/src/context.rs
=> Make `Context::new()` public (close #490)

actix/CHANGES.md, actix/src/io.rs
Refactor
Resolves the changes discussed in #498. `SinkWriter::write` should return a `Result` instead of an `Option`.
Closes #498.
=> Change return value to `Result` for `SinkWriter::write`

actix/CHANGES.md, actix/src/address/channel.rs, actix/src/address/mod.rs, actix/tests/test_address.rs
Feature
* `WeakRecipients`, like strong `Recipients` can now be cloned.
* `Recipient` now offers a `downgrade` method to obtain a `WeakRecipient`, similar to `Addr` and `WeakAddr`
* `WeakRecipient` can be converted from a `Recipient` via the `From` trait.
Potentially breaking changes:
* The `Sender` trait now requires a `downgrade` method. This affects code that implements its own `Sender` traits. However, this is not what many users would do.
Non-Breaking Changes:
* `WeakSender` is now public instead of crate-public. This did not use to be required, but the `downgrade` method on the publich `Sender` trait forces this.
Closes [#518](https://github.com/actix/actix/issues/518)
=> Implement Clone for WeakRecipient

actix/CHANGES.md, actix/src/address/channel.rs, actix/src/address/mod.rs, actix/tests/test_address.rs
Feature
We can now compare weak addresses for equality directly. In case two weak addresses `w1` and `w2` can both be upgraded, comparing `w1 == w2` will produce the same result as `w1.upgrade().unwrap() == w2.upgrade().unwrap()`. The same is true for the negation. If the weak addresses cannot be upgraded, the result still makes sense intuitively because it will check whether the weak address points to the same underlying actor, even if the actor is already destroyed.
There are no breaking changes, because `PartialEq` and `Eq` have been added to `WeakAddr` and `WeakAddressSender` and nothing else has been removed or changed.
Closes #523
=> implement `eq` for weak addr

actix/CHANGES.md, actix/src/handler.rs
Feature
This implementation allows for users to use `ActorResponse` with `Pin<Box<dyn ActorFuture + 'static>>` without causing double boxing.
=> Implement a From for ActorResponse to avoid double boxing

actix/README.md
Other: Documentation Fix
Not Applicable
Fixes two broken links in README.md by removing the square brackets around the URL. I found this because the links did work in VsCode preview of README.md. I then look at the README.md on github and noticed that the links didn't work on Safari, Chrome and Mozilla. After this change the links work on those and continue to work in the VsCode preview.
=> Fix broken links in README.md

actix/README.md
Other: Doc change
Not applicable
Prior to this change compiling this example generated the following warnings:
```
$ cargo run
warning: unused import: `Addr`
--> i-am-alive/src/main.rs:1:20
|
1 | use actix::{Actor, Addr, Context, System};
|                    ^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused variable: `addr`
--> i-am-alive/src/main.rs:17:9
|
17 |     let addr = system.block_on(async { MyActor.start() });
|         ^^^^ help: if this is intentional, prefix it with an underscore: `_addr`
|
= note: `#[warn(unused_variables)]` on by default
warning: unused variable: `ctx`
--> i-am-alive/src/main.rs:8:27
|
8 |     fn started(&mut self, ctx: &mut Self::Context) {
|                           ^^^ help: if this is intentional, prefix it with an underscore: …
```
=> Fix I am alive warnings

actix/CHANGES.md, actix/src/address/mod.rs
Feature
Derive the `PartialEq` and `Eq` traits for `MailboxError`. 
This is mainly a convenience change, it eases writing test cases with `assert_eq!`. Unless I am missing something there is no reason not to derive them.
=> Derive `PartialEq` and `Eq` for `MailboxError`

actix-broker/CHANGES.md, actix-broker/src/broker.rs, actix-broker/src/issue.rs, actix-broker/tests/delivery.rs
Bug fix
While the broker API is really not great, it did offer the guarantee of at-least-once delivery previously on `issue_async`.
Since the `do_send` doesn't return a result anymore, it was changed to a `try_send` which dropped the message on mailbox full.
This PR catches this error and will enqueue the message using `do_send`. I kept the first `try_send` to detect closed mailbox and detach them from the broker (which was the previous behaviour).
Ideally the broker would follow the same API as the actor and have something like a `do_send`, `try_send` and `send` instead. But this is a larger change that is out of scope for the current fix.
Closes #534
=> fix: ensure at least once delivery on broker IssueAsync

actix/src/lib.rs
Documentation Update
The top level crate documentation hasn't been updated in a long time.
* Updated MSRV
* Changed link from Gitter to Discord (since the Gitter doesn't exist anymore(?))
* Removed reference to `resolver` actor.
The line [`#![allow(deprecated)]`](https://github.com/actix/actix/blob/11379baf04ed6598f799034796ac4d266c2c3a99/actix/src/lib.rs#L34-L35) should be removed as well, but it doesn't have anything to do with the documentation.
https://github.com/actix/actix/blob/11379baf04ed6598f799034796ac4d266c2c3a99/actix/src/lib.rs#L34-L35
=> doc: update crate documentation in `lib.rs`

actix/CHANGES.md, actix/tests/test_fut.rs
Refactor
This fixed following deprecation warnings:
```
$ cargo test
Compiling actix v0.13.0 (/Users/yoshimin/src/github.com/actix/actix/actix)
warning: use of deprecated associated function `futures_util::stream::FuturesOrdered::<Fut>::push`: use `push_back` instead
--> actix/tests/test_fut.rs:56:11
|
56 |         s.push(sleep(Duration::from_millis(20)));
|           ^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: use of deprecated associated function `futures_util::stream::FuturesOrdered::<Fut>::push`: use `push_back` instead
--> actix/tests/test_fut.rs:57:11
|
57 |         s.push(sleep(Duration::from_millis(20)));
|           ^^^^
warning: `actix` (test "test_fut") generated 2 warnings
Finished test [unoptimized + debuginfo] target(s) …
```
=> fixed futures_util deprecation warnings

actix/CHANGES.md, actix/Cargo.toml
Other
futures-util v0.3.7 was already yanked. So update futures-util.
https://github.com/rust-lang/futures-rs/blob/master/CHANGELOG.md#037---2020-10-23
https://github.com/rust-lang/futures-rs/issues/2310
=> Update futures-util dependency

.github/workflows/ci-merged.yml, .github/workflows/ci.yml, .github/workflows/clippy-fmt.yml, .github/workflows/upload-doc.yml
Signed-off-by: Yuki Okushi <jtitor@2k36.org>
Other
actions-rs is currently unmaintained and most actions can be replaced by just using pre-installed rustup and invoking Cargo. One pain is AFAIK there's no great and popular alternative to clippy-check, I've selected https://github.com/giraffate/clippy-action as it has some nice features.
=> Upgrade GHA workflows to remove deprecation warnings

actix/src/fut/future/mod.rs
Docs
In reading [the ActorFuture docs](https://docs.rs/actix/0.13.0/actix/fut/future/trait.ActorFuture.html), I came across the following code:
```rust
// The response type returned by the actor future
type OriginalActorResponse = ();
// The error type returned by the actor future
type MessageError = ();
// This is the needed result for the DeferredWork message
// It's a result that combine both Response and Error from the future response.
type DeferredWorkResult = Result<OriginalActorResponse, MessageError>;
impl Handler<DeferredWork> for OriginalActor {
// Notice the `Response` is an `ActorFuture`-ized version of `Self::Message::Result`.
type Result = ResponseActFuture<Self, Result<OriginalActorResponse, MessageError>>;
...
```
While trying to …
=> Change to DeferredWorkResult in ActorFuture docs

actix/src/lib.rs
https://actix.rs/book/actix is 404. I believe https://actix.rs/docs/actix is what we want here.
=> docs: fix broken link

.github/workflows/clippy-fmt.yml, actix/CHANGES.md, actix/src/io.rs, actix/tests/test_sink.rs
Bug Fix 
Currently, SinkWriteFuture only sends the first item in the buffer when polled. If the underlying Sink is Ready, and doesn't trigger the waker, and no further items are written to the SinkWrite, then the other items in the buffer are never send at all, since poll isn't called again because the task of the context isn't woken.
This can be seen in the test I added, which hangs without my fix: The Sink there doesn't block (is ready) when the messages are single bytes, so only the first byte is received on the other side of the channel. The second await hangs forever.
The fix is to simply loop and try to send all items in the buffer, until either the buffer is empty or the underlying Sink isn't ready anymore.
This fix doesn't cause any breaking …
=> Add test for and fix issue with SinkWrite not sending items in buffer

actix/CHANGES.md, actix/src/contextimpl.rs, actix/tests/test_context.rs
Feature
Making possible to implement custom [`actix::Supervisor`] types.
[`actix::Supervisor`] does not allow to shutdown an [`actix::Actor`] it supervising. In this case a custom [`actix::Supervisor`] should be implemented by the user to satisfy it needs (graceful shutdown of a supervised [`actix::Actor`] via `Supervisor::shutdown` in my case for example). But there is no way to implement a custom [`actix::Supervisor`] type because [`actix::ContextFut::restart`] is crate-local and can't be used in usercode.
Make [`actix::ContextFut::restart`] public.
[`actix::Actor`]: https://github.com/actix/actix/blob/d7aab0a0f439679a570d08aaa6972ad8b60003de/actix/src/actor.rs#L75
[`actix::ContextFut::restart`]: …
=> Expose `actix::ContextFut::restart` to public API

.github/workflows/clippy-fmt.yml, actix/CHANGES.md, actix/src/actor.rs, actix/src/utils.rs, actix/tests/test_actor.rs
Feature
Add the ability to run a closure in a Context with a given start time. Useful for instance if you want to run the closure immediately on an actor's creation, and subsequently at some interval. 
Naming convention follows tokio's naming convention for the same behavior i.e. `tokio::time::interval_at`
=> Add run_interval_at to AsyncContext
