actix/actix

- examples/chat/README.md
> Stickler grammer changes

- src/registry.rs
> Fix bug in SystemRegistry

- src/constants.rs
- src/context.rs
- src/lib.rs
- tests/test_recursion.rs
> Fix memory leak when sending messages recursively to self

- README.md
Hi, I'm just learning about Actix actors so I decided to do a quick pass over the README. Thanks for the useful library!
> Quick proofread/spelling/grammar fixes to README

- guide/src/qs_01.md
- guide/src/qs_02.md
- guide/src/qs_03.md
- guide/src/qs_04.md
Same as for `actix-web` - I tried to improve the language a bit while reading through.
> Guide: improve wording & style

- src/handler.rs
> Add MessageResponse for Option<T>

- src/actor.rs
- src/utils.rs
- tests/test_actor.rs
> Add run_interval method for AsyncContext

- src/address/channel.rs
As subj states it makes `maybe_parked` wrapped into Atomic so that `AddressSender` and consequently `Addr` would be `Send` and `Sync` and it would allow us to store it in `actix-web` state
> AddressSender to use AtomicBool to allow Addr to be Sync/Send

- src/io.rs
>Unless the task is notified, the buffer isn't always flushed out after
every write. The actor's poll method would return NotReady when the
buffer empties without setting up a way to be notified when the buffer
was written to again.
> Notify the io::InnerWriter's task if necessary

- tests/test_actor.rs
- tests/test_address.rs
Let's see how appveyor would handle it now
> Improve timing related tests

- examples/ping.rs
- src/actor.rs
- src/arbiter.rs
- src/registry.rs
I was reading through the source to learn more about this cool project.
Fixed a few tiny typos that I noticed via this PR.  (`It's` is a contraction of "it is".  The possessive is `its`.)
> Tiny grammar and spelling fixes.

- src/address/mod.rs
The first step in resolving actix/actix-web#528.
I think there will need to be an actix release between when this PR gets merged and when the other patch goes into actix-web.
> Make SendError Fail when possible.

- src/address/channel.rs
- src/registry.rs
- tests/test_address.rs
- tests/test_arbiter.rs
- tests/test_context.rs
PR with last changes requested on #152. :)
> Fix some clippy warnings

- src/address/channel.rs
- src/address/mod.rs
- src/arbiter.rs
- src/context.rs
- src/contextimpl.rs
- src/handler.rs
- src/mailbox.rs
- src/registry.rs
- src/supervisor.rs
- src/system.rs
I've implemented Debug trait for public structures from prelude except for MessageResult and Recipient.
https://github.com/actix/actix/issues/135
Closes #135
> An implementation of Debug trait for public structs

- src/actors/resolver.rs
> fix actors/resolver.rs doc comment

- CHANGES.md
- src/system.rs
> Make Syste::stop_with_code public

- CHANGES.md
- MIGRATION.md
- src/handler.rs
Closes #200 
Need to update actix-web immediately after releasing actix https://github.com/actix/actix-web/tree/async_keyword_usage
> Remove async function from Response and ActorResponse

- Cargo.toml
- examples/ring.rs
This should offer a benchmark that can be run against each version and satisfied much of #52.
> Add ring test. Also cargo run --release --example ping doesn't work with LTO

- CHANGES.md
- src/address/channel.rs
- src/address/mod.rs
Recipient abstraction extended to have a way to check aliveness of actual actor.
> Add connected function to Recipient, Sender and AddressSender

- src/address/mod.rs
> Remove unexpected semicolon

- src/handler.rs
This way a message can return an Arc which can be useful.
> Implement MessageResponse for Arc

- src/io.rs
> Add flush to `FramedWrite` on drop

- CHANGES.md
- src/handler.rs
I'd like to add tests but there's not really behavior. Happy to add them if you can think of any to run.
> Add implementations for `Message` for `Arc` and `Box`

- src/fut/mod.rs
I felt the example was a little lacking when learning about it, so I think the more explicit comments are helpful here. I also removed a syntax error.
Personally, I think this example is a little too complicated to get the point across. It's somewhat unclear where `ActorFuture` even comes in. The fact that we `send` at all is unnecessary and I would have preferred to use a more generic `Future` to demonstrate that the point of `ActorFuture` is just to add `Actor` data to a `Future` (which has little to nothing to do directly with `send`ing, as far as I can tell).
> Improve example for `ActorFuture`

- src/lib.rs
- tests/derive.rs
- tests/test_actor.rs
- tests/test_fut.rs
Changed a few tests to reflect/test to make sure compilation still works as expected.
> Add `futures::{future, Stream}` to actix::prelude::*

- CHANGES.md
- src/address/mod.rs
See https://github.com/actix/actix/issues/249
> Implement std::errror:Error for SendError

- src/address/mod.rs
> Add Debug impl for Recipient

- README.md
We can choose to remove the note or point to another location.
Fixes #267
> Update README about signal

- README.md
Follow the latest minor version
> Update actix version on README

- .travis.yml
- README.md
> Run CI on MSRV

- src/fut/mod.rs
The example for the use of `ResponseActFuture` on `ActorFuture` doc was outdated for actix v0.9, I've swapped the `ignore` for a `norun` on the doc to make the error actually visible by the build system and updated the example so it can work with the most recent version of Actix.
> Fix doc example for fut::ActorFuture

- src/io.rs
The struct `WriterFut` is private, and is only ever constructed when
`T: Unpin` is known to hold. This lets us add a `T: Unpin` bound to the
definition of `WriterFut`, and use `Pin::new` instead of
`Pin::new_unchecked`.
> Remove uses of `Pin::new_unchecked` in `WriterFut`

- README.md
The current badge causes mixed content on crates.io.
> Fix mixed content

- CHANGES.md
- src/sync.rs
On scenarios where you want to do "recursive" calls this may help
This is old pull #257 on current master
> Add address to SyncContext

- codecov.yml
ref. https://docs.codecov.io/docs/commit-status
> Make CI green even if coverage gets worse

- CHANGES.md
- src/contextimpl.rs
- src/handler.rs
- Fix typos
- Extract the changelog entry that should be in next release
> Tweak documentation

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
> Update `actions/cache` to v2

- README.md
Added a name to both Actors to better show that the ping is happening between the actors. It wasn't obvious what the console output meant.
> Update README.md example to be more verbose

- CHANGES.md
- src/address/channel.rs
- src/address/mod.rs
> add std::marker::Sync for Sender trait

- src/supervisor.rs
Documentation Enhancement
Simple documentation enhancement for Supervisor.
> enhance supervisor documentation

- .github/workflows/macos.yml
- CHANGES.md
- Cargo.toml
- LICENSE-APACHE
- LICENSE-MIT
- README.md
- examples/chat/README.md
- examples/chat/src/main.rs
- examples/chat/src/session.rs
- src/fut/mod.rs
- src/lib.rs
- src/supervisor.rs
- tests/derive.rs
Release / Docs
closes #337, #370
> prepare v0.10 release

- .github/workflows/macos.yml
> reinstate macos ci cache

- CHANGES.md
- Cargo.toml
Bug Fix
Fix #426 :
> Build with --no-default-features fail: could not find `sink` in `futures_util`
Closes #426
> Fix error for build with --no-default-features

- .github/workflows/upload-doc.yml
`ghq-import` has updated recently and now causes failure: https://github.com/actix/actix/runs/1146605365
> Use `github-pages-deploy-action` instead of `ghq-import`

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
Sadly, the failure comes here as well :( https://github.com/actix/actix/pull/435/checks?check_run_id=1255415009
> Disable macOS cache on GHA

- CHANGES.md
- Cargo.toml
> Bump pin-project to 1.0

- CHANGES.md
- Cargo.toml
- README.md
- examples/chat/src/client.rs
- examples/chat/src/main.rs
- examples/fibonacci.rs
- examples/ping.rs
- examples/weak_addr.rs
- examples/weak_recipient.rs
- src/actors/resolver.rs
- src/lib.rs
Feature
Re-export `main` macro, just like actix-web.
Closes #415
> Re-export `main` entry point macro as `actix::main`

- CHANGES.md
- src/handler.rs
Refactor
Some code which had left Futures old code, which used separate `Item` and `Error` parameters.
> Unify MessageResponse impls

- CHANGES.md
- Cargo.toml
- README.md
- actix-derive/tests/test_macro.rs
- src/actor.rs
- src/context.rs
- src/contextimpl.rs
- src/stream.rs
- src/supervisor.rs
- src/utils.rs
Refactor
Fix examples due to change of https://github.com/actix/actix-net/pull/207
> fix system start examples with break change of actix-rt

- Cargo.toml
- actix-broker/CHANGES.md
- actix-broker/Cargo.toml
- actix-broker/LICENSE-APACHE
- actix-broker/LICENSE-MIT
- actix-broker/README.md
- actix-broker/examples/actix-web.rs
- actix-broker/examples/basic.rs
- actix-broker/src/broker.rs
- actix-broker/src/issue.rs
- actix-broker/src/lib.rs
- actix-broker/src/msgs.rs
- actix-broker/src/subscribe.rs
- actix-broker/tests/general.rs
Other
Migrates actix-broker crate to be first party.
Hey @chris-ricketts, it's on my mind to do this before the next major release. In particular I need your approval on the additions to the license files (8fbe28fdb3ed4ccdd4d0fd409f2875ad558f111c).
Supercedes https://github.com/actix/actix-extras/pull/122.
> migrate Chris-Ricketts/actix-broker

- README.md
Other
While I was reading the README, I noticed a few places where I thought the wording could be better.
> Tweak English of README

- Cargo.toml
- actix/src/address/channel.rs
- actix/src/address/queue.rs
Bug Fix
Update futures-channel to latest master branch.
> bump futures channel

- actix/src/actors/resolver.rs
- actix/src/contextitems.rs
- actix/src/handler.rs
- actix/src/stream.rs
Refactor
Clean up generic types.
> clean up generic types

- actix/src/address/channel.rs
- actix/src/address/message.rs
- actix/src/address/mod.rs
Refactor
Reduce duplicate code by using single request type for both normal and recipient message.
> reduce duplicate code/use single request type

- actix/tests/test_address.rs
Bug Fix
Relax the timeout in `test_message_timeout`
> releax timeout in test_message_timeout

- actix/src/utils.rs
Other
Use pinned `Sleep` type instead of `Pin<Box<Sleep>>` in `IntervalFunc`.
Deprecated `Condition` type. This type is years old with no internal usage and is only a wrapper around `Vec<tokio::sync::oneshot::Sender>`.
> use pinned sleep instead of boxed interval

- actix/src/contextimpl.rs
Bug Fix
Merge context parts when there is new wait item.
This is a temporary fix that would make the related issue case work.
At the root the separation of context parts and context items is error prone and I believe it would be better to eat some cost and unify them to a single container.
This fix may also cause behavior change and potential breaking for some user code. As the merge happens early and with every poll of  concurrent message.
Closes #458
> early merge on every poll of message.

- actix-broker/CHANGES.md
- actix-broker/Cargo.toml
- actix-broker/README.md
- actix-derive/CHANGES.md
- actix-derive/Cargo.toml
- actix-derive/README.md
- actix/CHANGES.md
- actix/Cargo.toml
- actix/README.md
- actix/examples/README.md
- actix/src/actors/mod.rs
- actix/src/actors/resolver.rs
- actix/src/fut/future/either.rs
- actix/src/fut/future/mod.rs
- actix/src/fut/future/result.rs
- actix/src/fut/mod.rs
- actix/src/lib.rs
Release
- Remove some useless re-exports.
- Cut 0.11 release.
```
0.10 : 48.8 sec
0.11 : 29.6 sec
~40% improvement
```
```
cargo run --release -- 1000 16000
1,000 nodes
16,000 rounds
0.10 : 13.366569 seconds (1,197,016 msg/second)
0.11 :  7.253802 seconds (2,205,739 msg/second)
~2x speedup
```
> release 0.11

- actix-derive/src/message.rs
Other (minor error message edit)
Improves the grammar in an error message.
Closes #487
> Minor error message edit.

- actix/CHANGES.md
- actix/src/fut/future/mod.rs
- actix/tests/test_fut.rs
Feature
As a shortcut for `Box::pin`
> Add ActorFutureExt::boxed_local method

- actix/CHANGES.md
- actix/src/handler.rs
- actix/tests/derive.rs
- actix/tests/test_actor.rs
- actix/tests/test_atomic_response.rs
- actix/tests/test_connected.rs
- actix/tests/test_context.rs
- actix/tests/test_messages.rs
- actix/tests/test_sink.rs
Signed-off-by: Bart Willems
Feature
This PR allows responding with std Vec for message responses.
> implemented MessageResponse for Vec<T>

- actix-broker/CHANGES.md
- actix-broker/Cargo.toml
- actix-broker/README.md
- actix-derive/Cargo.toml
- actix/CHANGES.md
- actix/Cargo.toml
- actix/README.md
> prepare actix 0.12.0 release

- actix/src/address/message.rs
Documentation Update
Fixes a typo in an error message and improves its readability.
> Fix typo and improve MsgRequest must_use readability.

- actix/examples/README.md
- actix/examples/mock.rs
Docs
The [mocker docs](https://docs.rs/actix/0.12.0/actix/actors/mocker/index.html) mentions a mock example. I couldn't find it anywhere, so I thought that maybe I could contribute with one. 
I've seen two questions on Reddit about how to use it,([1](https://www.reddit.com/r/actix/comments/aacbtr/examples_of_mocker_usage/), [2](https://www.reddit.com/r/actix/comments/aacbtr/examples_of_mocker_usage/)), so I figured this example might be helpful to others.
> Mock example added

- actix/README.md
Bug Fix (docs)
Tested those links again in README.
Fixes 3 broken links in current README.
There shouldn't be any breaking changes (?).
Closes #558
> docs: fix broken links in README (#558)
